spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo
    username: postgres
    password: 123456
  flyway:
    locations: classpath:db-migration
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
